# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# Stop uploading usage metrics to fastlane devs
opt_out_usage

default_platform(:android)

platform :android do
  desc "Clean Android build"
  lane :clean do
    gradle(
      task: "clean"
    )
  end

  desc "Build and assemble APK"
  lane :assemble do
    gradle(
      task: "assemble",
      build_type: "release"
    )
  end
end
